# Generated by Django 4.2 on 2024-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(default='Tier 1', max_length=25),
            preserve_default=False,
        ),
    ]
