# Generated by Django 4.2 on 2024-09-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_subscription_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo',
        ),
    ]
