# Generated by Django 4.2.10 on 2024-05-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('capital', models.DecimalField(decimal_places=0, max_digits=15)),
                ('impact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sdg', models.JSONField()),
                ('values', models.JSONField()),
                ('expertise', models.JSONField()),
                ('matching', models.JSONField()),
                ('strategy', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
