# Generated by Django 4.2 on 2024-08-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_experience', models.TextField()),
                ('languages', models.JSONField()),
                ('values', models.JSONField()),
                ('motives', models.JSONField()),
                ('members', models.JSONField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_section', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField()),
                ('customer_problem', models.TextField()),
                ('unique_selling_point', models.TextField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offerings_section', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMatchingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.JSONField()),
                ('investor_qualities', models.JSONField()),
                ('investment_instrument', models.JSONField()),
                ('exit_strategy', models.JSONField()),
                ('investor_expertise', models.JSONField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_section', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_market', models.TextField()),
                ('number_of_competitors', models.PositiveIntegerField()),
                ('market_size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CAGR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scalability', models.TextField()),
                ('competitors', models.JSONField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_section', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_level', models.PositiveIntegerField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_section', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_required', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stage', models.CharField(max_length=100)),
                ('investor_count', models.CharField(max_length=100)),
                ('use_of_funds', models.JSONField()),
                ('financial_statement', models.JSONField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials_section', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_address', models.CharField(max_length=255)),
                ('company_code', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('mission', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('legal_form', models.CharField(max_length=50)),
                ('target_group', models.JSONField()),
                ('founding_date', models.DateField()),
                ('website_url', models.URLField()),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details_section', to='api.startup')),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_details', to='api.startupdetails'),
        ),
        migrations.AddField(
            model_name='startup',
            name='financials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_financials', to='api.startupfinancials'),
        ),
        migrations.AddField(
            model_name='startup',
            name='impact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_impact', to='api.startupimpact'),
        ),
        migrations.AddField(
            model_name='startup',
            name='market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_market', to='api.startupmarket'),
        ),
        migrations.AddField(
            model_name='startup',
            name='offerings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_offerings', to='api.startupoffering'),
        ),
        migrations.AddField(
            model_name='startup',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_preferences', to='api.startupmatchingpreferences'),
        ),
        migrations.AddField(
            model_name='startup',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_team', to='api.startupteam'),
        ),
        migrations.CreateModel(
            name='InvestorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_market', models.TextField()),
                ('languages', models.JSONField()),
                ('funding_stage', models.JSONField()),
                ('investment_instrument', models.JSONField()),
                ('exit_strategy', models.JSONField()),
                ('qualities', models.JSONField()),
                ('expertise', models.JSONField()),
                ('team_values', models.TextField()),
                ('impact_level', models.PositiveIntegerField()),
                ('target_group', models.JSONField()),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_section', to='api.investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previously_invested', models.JSONField()),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_section', to='api.investor')),
            ],
        ),
        migrations.AddField(
            model_name='investor',
            name='portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_porfolio', to='api.investorportfolio'),
        ),
        migrations.AddField(
            model_name='investor',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_preferences', to='api.investorpreferences'),
        ),
    ]
