# Generated by Django 5.0.4 on 2024-05-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PS', 'PS'), ('SA', 'SA'), ('SB', 'SB'), ('SC', 'SC'), ('BG', 'BG')], default='PS', max_length=2)),
                ('industry', models.CharField(choices=[('FN', 'FN'), ('AG', 'AG'), ('TE', 'TE'), ('MO', 'MO')], default='FN', max_length=2)),
                ('location', models.CharField(choices=[('RW', 'RW'), ('GH', 'GH'), ('NG', 'NG')], default='RW', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='location',
            field=models.CharField(choices=[('RW', 'RW'), ('GH', 'GH'), ('NG', 'NG')], default='RW', max_length=2),
        ),
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.CharField(choices=[('FN', 'FN'), ('AG', 'AG'), ('TE', 'TE'), ('MO', 'MO')], default='FN', max_length=2),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('PS', 'PS'), ('SA', 'SA'), ('SB', 'SB'), ('SC', 'SC'), ('BG', 'BG')], default='PS', max_length=2),
        ),
    ]
