# Generated by Django 4.2 on 2024-08-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_investorpreferences_team_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorpreferences',
            name='ticket_size',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
