# Generated by Django 4.2 on 2024-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investorpreferences_ticket_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorpreferences',
            name='industry',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
