# Generated by Django 4.2 on 2024-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_investor_category_investor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupmarket',
            name='number_of_competitors',
            field=models.CharField(max_length=100),
        ),
    ]
