# Generated by Django 4.2 on 2024-09-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_startupmarket_number_of_competitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='investor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='location',
        ),
        migrations.AddField(
            model_name='investor',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='investor',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_details', to='api.investordetails'),
        ),
    ]
