# Generated by Django 4.2 on 2024-08-29 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matcher', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matching',
            unique_together={('user', 'matched_with')},
        ),
    ]
